### ISSUE TITLE
Space Conservation

### ISSUE THREAD

**Issue by crispd** [crispd/issues#1]
to first order:
1)READ, RSET, and SET columns could stand to be shortened by 40-50%.
2)Device Rows in opstuner are about 50% taller than those in the ROLS tuning screens. When font is likely decreased two things could be done to maintain readability of screen: boldening the font, and increasing the contrast between font color and background (As in 'READ': Yellow vs Blue).

![11-11-2014_opstuner--rols](https://cloud.githubusercontent.com/assets/7905813/4996257/65843bba-6994-11e4-8257-b0a3cb63a0df.JPG)

**Comment by crispd** [comment]
An update as of 11/20/2014: Widget sizes have been drastically decreased to conserve screen space.
Issue #2 has also been addressed by making it more apparent which device is subject to change upon action. This was done using the orange highlight method used in current ROLS Tuning Screens.
![tuningapplayout](https://cloud.githubusercontent.com/assets/7905813/5147024/34d8a750-7180-11e4-8362-cad096a24f88.png)

**Comment by crispd** [comment]
Space conservation is an issue that is always a high priority, as features are manipulated we may need to revisit their effect on screen conservation. But as long as these current effects are seen across OS platforms we can consider this issue or requirement item # satisfied.
Ongoing Question regarding this recent improvement: Regarding the object of issue #2 we should continue the development/discussion regarding how best to indicate secondarily selected devices (devices other than the primary selection which are subject to change on the operators set point action).

**Comment by dxmaxwell** [comment]
An updated screen shot running the Tuning Application on Windows 7.  The names have been changed to bold style to improve legibility. 
![tuningapplayoutwin7](https://cloud.githubusercontent.com/assets/109703/5148840/d252c6b8-7190-11e4-8623-7649735c8687.png)

**Comment by crispd** [comment]
This meets all requirements in this thread. And completely addresses the specific boldened requirement described in Requirement Item #2 .
