### ISSUE TITLE
Alternative keyboard shortcuts for adjusting 'Stepping Factor'

### ISSUE THREAD

**Issue by crispd** [crispd/issues#12]
Regarding Issue #10 Key conflicts.
3 main functions are currently being used to adjust the 'Stepping Factor'. Setting the Factor using large multipliers, small multipliers, and resetting it to 1.
While holding the 'Left Ctrl' key, the Left and Right arrow keys perform large adjustments: x1/10, x10.
While holding the 'Left Alt' key, the Left and Right arrow keys perform small adjustments: x1/2, x2.
While holding either 'Left Ctrl' or 'Left Alt', the Down arrow key resets the 'Stepping Factor' to 1x.

**Comment by dxmaxwell** [comment]
Wanted to clarify in the description above that 'Left Ctrl' and 'Left Alt' could simply be 'Ctrl' and 'Alt' because with these new key combinations there would be no distinction between 'Left' and 'Right' keys.

**Comment by crispd** [comment]
I should add the convenience being created with the keyboard shortcuts on the left side of the keyboard in conjunction with the arrow keys. And that with the Ctrl and Alt keys already symbolizing large and small adjustments to the 'Stepping Factor', the change in functionality remains intuitive.

**Comment by crispd** [comment]
I'm glad you pointed this out. It doesn't impede the functionality, but may nag at people used to the space bar key solution. It isn't possible to have both for a test allowing someone to see what they think of the two methods is it? If both methods exist simultaneously you may have to suppress the extra adjustment that would be made when releasing either 'Ctrl' or 'Alt' (after they had been held to intentionally adjust using the arrow method.)

**Comment by dxmaxwell** [comment]
I will need to do some testing to determine if both the old and new methods
can co-exist somewhat peacefully.  I'll try to make it work.

**Comment by crispd** [comment]
It appears that this does work as expected, and does not have any issues existing with legacy controls. I will close this issue, as the intended result was realized. If we can additionally move away from using the alt key in addition to the space bar then it would be suggested in a separate Issue# related to #10
