### ISSUE TITLE
Enable/Disable ALL checkbox

### ISSUE THREAD

**Issue by crispd** [crispd/issues#13]
The screen now comes up disabled, as it should. And an initial click on the enable all checkbox will enable all devices as expected. The Issue is this checkboxe's ability to be toggled back and fourth in intervals of at least 2 seconds. I notice when removing focus from the screen, then trying the checkbox again that it will work but I have to do that each time I want to check or uncheck the box.

**Comment by crispd** [comment]
Upon re-creating this issue, this checkbox toggled as expected, I'm unsure why it didn't seem to work  well at first.

**Comment by crispd** [comment]
This is a reacurring issue, I'm unsure what triggers it. But there are times when the checkbox can not be correctly toggled. The issue is not related to the time one must allow for all devices to be enabled or disabled.

**Comment by dxmaxwell** [comment]
I have not been able to reproduce this behavior on my own Win7 VM. I would
not be entirely surprised it there was an issue because I'm doing something
unusual with the focus on checkboxes to try and work around the "spacebar
problem".

**Comment by crispd** [comment]
Well the issue is somewhat intermittent.. possibly indicating that it won't be easily reproduceable. Is there any way that unfocusing the checkbox disallows a successive refocus? Something that is more properly done when focusing on an exterior window that isn't happening after you 'defocus' the checkbox for the space bar?

**Comment by crispd** [comment]
This seems to have been solved with the update that was tested ~30 April.
