### ISSUE TITLE
Increasing Color Contrast

### ISSUE THREAD

**Issue by crispd** [crispd/issues#14]
Goal: Increase the ease one can read the text on the screen.
Suggested Approach: Boldening the font; utilizing the Yellow on Blue, and Black on Cyan color scheme.
There may be better color combinations, but using this color scheme would help make the screen appear more familiar.
![opstunercontrast](https://cloud.githubusercontent.com/assets/7905813/5304660/db171b5a-7bc2-11e4-985b-51222d17e9c8.JPG)
![rocs_contrast](https://cloud.githubusercontent.com/assets/7905813/5304747/b34d9ec2-7bc3-11e4-888f-56a60e4c6f1a.JPG)

**Comment by crispd** [comment]
I've accepted the related pull request on stash, could you please post a snapshot of your improvement in this thread? I'd like these to be complete threads when they're closed out.

**Comment by dxmaxwell** [comment]
Updated Tuning Application to be more consistent with original application.

![tuningcolors](https://cloud.githubusercontent.com/assets/109703/5494267/9053e20c-86c0-11e4-9386-fe2fce31acb8.png)

**Comment by crispd** [comment]
Thank You!
