### ISSUE TITLE
Colors in Settings Dialog

### ISSUE THREAD

**Issue by dxmaxwell** [crispd/issues#16]
The colors of the fields in the settings dialog window does not match the main window.

**Comment by crispd** [comment]
![2-3-15_tun_menucolors](https://cloud.githubusercontent.com/assets/7905813/6025024/6850653a-ab9d-11e4-9e45-87711c852e8f.JPG)
I take it that this is what you mean by this? Additionally the font is not emboldened.

**Comment by crispd** [comment]
This was solved with the updated version tested on ~30 April.
