### ISSUE TITLE
Gaining Groups (Functionality)

### ISSUE THREAD

**Issue by crispd** [crispd/issues#3]
Gaining Groups
-When a device of a given group is selected, all devices within that group should indicate they too are subject to changes made when setting the primary device. (Mentioned in Issue#2:Look)
-Say two devices are being gained together, one negative, the other positive. When the primary device selection is the positive of the two, using the right arrow increases the set of the primary device, and decreases the set of the negatively gained device. This is good. BUT when the primary device selection is the negative of the two, using the right arrow decreases the set of the primary device, and increases the set of the positively gained device. This is not an intuitive functionality.

**Comment by crispd** [comment]
This should be discussed. Currently when inversely gained, the primary selection always does what the user intends it to, whereas the secondarily gained device(s) does the opposite.

If we keep the functionality of inversely gained groups as they are on your screen currently, I would argue that more should be done to indicate the variance in function from the screen it is intended to replace.

**Comment by dxmaxwell** [comment]
Unable to reproduce the behavior described above.  The primary device selection always moves as the user indicates (right arrow == positive), even if it is negatively ganged.

**Comment by crispd** [comment]
This is curious. there shouldn't be a difference depending on OS used should there? I can try this again on a ReA windows machine. If this can't be replicated than we can close this thread.
How to indicate a secondarily selected device via ganging is a discussion for #2 . Whether or not it is necessary now to indicate which devices will be set inversely from the primary selection is up for discussion: this is somewhat less required if this thread's issue isn't reproduce-able.

**Comment by dxmaxwell** [comment]
It shouldn't depend on the OS being used. But to be safe I was testing on my Win 7 VM.  Perhaps there is a more subtle bug.

**Comment by crispd** [comment]
I will see what I can do to test it on the ReA machine, it is possible that something of it's environment is different. I believe there was an update since the last testing, I'll report what I find out (time for another thorough testing/results from a quick test.)

**Comment by crispd** [comment]
This has been sufficiently dealt with and noted (complete with picture) in Issue #1 .
