### ISSUE TITLE
RST and ON buttons.

### ISSUE THREAD

**Issue by crispd** [crispd/issues#7]
a. Interlock conditions were created and devices interlocked off as a result. Both ON and Interlock status indicators turned red, as expected. But once the interlock conditions were corrected the individual RST and ON buttons did not reset or turn on devices. 'All On' and 'RST All' buttons work on all devices, but their device specific counterparts did not.

**Comment by dxmaxwell** [comment]
The individule ON/OFF buttons work properly on Linux, but not on Windows.  There must be some platform specific behavior with the state (ie true/false) of the button at the time it is pressed.

**Comment by dxmaxwell** [comment]
The problem is related to an attempted work around I had implemented to deal with #10, but it did not work properly on Windows.

**Comment by crispd** [comment]
The new version is updated on the ReA machine we've been testing on. The Individual On and Off buttons work as expected with the new fix. However, I am unable to test the RST buttons until we are able to simulate an interlock scenario.

**Comment by crispd** [comment]
The RST and ON/OFF buttons appear to work, though now the clear all seems to be intermittent. That being said, I believe the alarm functionality is changing as a result of changed specifications in the current workorder for the opstuner project: making the clear all issue irrelevant to new scope of project.
